# version: '3.8'
services:
    mongodb:
        image: mongodb/mongodb-community-server
        container_name: mongodb
        ports:
            - 27017:27017
        volumes:
            - type: bind 
              source: D:/DataBase/MongoDB/DockerMount/data
              target: /data/db
        environment:
            # MONGO_INITDB_ROOT_USERNAME: user
            # MONGO_INITDB_ROOT_PASSWORD: pass
            MONGO_INITDB_DATABASE: test